---
collections:
  - name: ibm.ibm_zos_core
    version: 1.6.0
  - name: ibm.ibm_zos_ims
    version: 1.2.0
  - name: operator_sdk.util
    version: "0.4.0"
  - name: kubernetes.core
    version: "2.4.0"