---
#
# Copyright 2023 IBM Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# The SSID for the IMS to be provisioned
DFS_IMS_SSID: IMWZ

# IMSPlex name
DFS_IMSPlex: PLXWZ

# ---------------------------------------------------------------------------- #
#                               TCPIP information                              #
# ---------------------------------------------------------------------------- #
ODBM_PORTID: 9800
ODBM_SSLPORTID: 9801

# TLS port for IMS Connect
IMS_CONNECT_PORT: 9900
# TLS Port for IMS Connect
IMS_CONNECT_SSLPORT: 9901

# The API key to use for artifactory repositories
api_key: ''

k8s_cr_event: create
zos_job_submit_wait: false
zos_job_submit_wait_s: 120
zos_job_submit_return_output: false



# The user ID to use for IMS related provisioning steps
DFS_IMS_USERID: '{{ TARGET_USERNAME | upper }}'

# ---------------------------------------------------------------------------- #
# The first HLQ to be used to store IMS related datasets
# these include procs, OLDS, WADS, PROCLIB, JOBS, and application
# specific datasets
DFS_AUTH_LIB_HLQ1: IMSTEST
# The second HLQ to be used to store IMS related datasets
# these include procs, OLDS, WADS, PROCLIB, JOBS, and application
# specific datasets
DFS_AUTH_LIB_HLQ2: '{{ DFS_IMS_SSID }}'
# ---------------------------------------------------------------------------- #
# The first HLQ for system datasets that will be used
# by IMS during provisioning. These should exist prior to
# running playbooks
DFS_AUTH_LIB_SYSHLQ1: DFSF10
# The second HLQ for system datasets that will be used
# by IMS during provisioning. These should exist prior to
# running playbooks
DFS_AUTH_LIB_SYSHLQ2:

DFS_AUTH_LIB_SYSHLQ:

ZOS_RELEASE: ''

STEPLIB: '{{DFS_AUTH_LIB_SYSHLQ1}}.SDFSRESL'

DFS_INIT_JAVA_CONF: false

# Optimizes runtime if user is provisioning IMS
reconcile_run: false

# ---------------------------------------------------------------------------- #

# ---------------------------------------------------------------------------- #
#  Common Services related settings                                            #
# ---------------------------------------------------------------------------- #
OM_CONFIG: false

# ---------------------------------------------------------------------------- #
#                            storage related settings                           #
# ---------------------------------------------------------------------------- #

# Are the volumes we want to use managed by the storage management subsystem (SMS)?
DFS_SMS_ENVIRONMENT: true

# ------------------- Storage Management Subsystem settings ------------------ #
# -------------------------- used when SMS is in use ------------------------- #
# If the volumes are managed by SMS, what SMS storage class should be used?
# DFS_SMS_CLASS: SCNOSMS       # SCNOSMS does not work as expected
DFS_SMS_CLASS: SCIMS

# If the volumes are managed by SMS, what SMS management class should be used?
DFS_SMS_MCLASS: NONE

# -------------------------- volume related settings ------------------------- #
# ------------------------ for when SMS is not in use ------------------------ #

# first volume to use to store IMS datasets
DFS_DS_VOLUME1: ''

# second volume to use to store IMS datasets
DFS_DS_VOLUME2:

# ---------------------------------------------------------------------------- #
#                             Java related settings                            #
# ---------------------------------------------------------------------------- #

# The location to create and reference the profile that has environment settings and JVM options.
JAVA_CONF_PATH: '{{DFS_workingdir}}/dfsjvmpr.props'
REGION_NUM: 1

# Working directory for the IMS Java region (JMP)
DFS_workingdir: /u/{{ TARGET_USERNAME }}

DFS_IMS_UNIT: SYSALLDA
DFS_IMS_UNIT2: 3390
ODBM_PORTIDSuf: 99
DFS_IMSXCFGroup: IMSXCFGN

DFS_IMS_CRC: '@'
DFS_IMS_LINEGRP: SPOOL

# DFS_MOUNTPOINT: /usr/lpp/ims/ims13/imsjava
# DFS_FSTYPE: HFS

DFS_useRRS: 'N'

# DFS_VTAM_NODE_IMSMTO: PMASTER1
# DFS_VTAM_NODE_IMSND1: USER0001
# DFS_VTAM_NODE_IMSND2: USER0002


# IST_VTAM_Procedure: VTAM
# EZB_TCPIP_LoadLib: SYS1.TCPIP.LINKLIB
# GIM_IMS_TARGETzone: IMSTZ13
# GIM_IMS_GLOBALzone_CSI: IMSCLOUD
# zCloud_LPALIB: SYS1.LPALIB
# zCloud_VTAM_VTAMLIST: SYS3.VTAMLST
# zCloud_VTAM_VTAMLIB: SYS3.VTAMLIB
# zCloud_VTAM_VOL: IMSCLS
# zCloud_VTAM_DEV: SYSALLDA
# zCloud_IMS_DEV: SYSALLDA
# zCloud_IMSConnect: HWS1

DFS_useIEFJOBS: 'N'
zCloud_IEFJOBS: SYS1.IEFJOBS
DFS_IXUSTIM1: 300

# DFS_IXUSTIM3: 1440

DXR_IRLM_SSID: XRLM
DXR_IRLM_Procedure: IRLM23D

CSQ_SSID: CSQ1

## SVC Values
zCloud_IMS_SVC_Type2: '203'  #'229'
zCloud_IMS_SVC_Type4: '202'  #'249'



