#
# Copyright 2023 IBM Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
ansible_python_interpreter:  /usr/lpp/IBM/cyp/v3r10/pyz/bin/python3
PYZ: /usr/lpp/IBM/cyp/v3r10/pyz
ZOAU: /usr/lpp/IBM/zoautil
JAVA: /usr/lpp/java/java180/J8.0_64/bin
COBOL: /usr/lpp/cobol/cob630/igyv6r3/bin
STEPLIB: DFSF10.SDFSRESL

# vars_folder_name is the name of te folder at the root of the project
# which contains variable files to be imported by various playbooks
# this is done to separate variable values when they may be different between environments
# for example:
#  vars_files:
#    - "{{ vars_folder_name }}/ims-dbdc.yml"
# vars_folder_name: vars_broker
vars_folder_name: vars_wazi

# The z/OS username to use for job submission
TARGET_USERNAME: '{{ ansible_user }}'

# Where to install MVSUTILS/MVSCMD and other needed tools/scripts
uss_utilities_path: /u/{{ TARGET_USERNAME }}

# Where generated JCL files should be saved on target
# this is a defalult value that should be overwritten
# with a temporary directory for easier cleanup at the
# end of a playbook
uss_file_path: /u/{{ TARGET_USERNAME }}

JOB_CLASS:
MSG_CLASS:

# The user ID to use for IMS related provisioning steps
DFS_IMS_USERID: '{{ TARGET_USERNAME | upper }}'

# Working directory for the IMS Java region (JMP)
DFS_workingdir: /u/{{ TARGET_USERNAME }}

system_environment:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin:/usr/sbin:{{ JAVA }}:{{ COBOL }}"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  STEPLIB: "{{STEPLIB}}"