---
###############################################################################
# © Copyright IBM Corporation 2023
###############################################################################
# Default vars for ims dataset services
work_dataset: ""
sysdef_datasets: ""
runtime_datasets: ""
system_datasets: ""