---
###############################################################################
# © Copyright IBM Corporation 2023
###############################################################################
# Check if IMS already up
- name: Check for duplicate IMS
  collections:
      - ibm.ibm_zos_core
      - ibm.ibm_zos_ims
      
  block:
    - name: Searching for IMS {{ DFS_IMS_SSID }}
      zos_operator:
        cmd: 'd a,{{ DFS_IMS_SSID }}CTL'
      register: ctl_output

    # IMS already up, a reconcile comes in, try to reconcile
    - block:
        - debug: 
            msg: 'IMS {{ DFS_IMS_SSID }} already up. Trying to reconcile....'
        - set_fact:
            ims_is_up: true
        # - meta: end_host
      when: 
        - reconcile_run
        - ctl_output.content is defined and "NOT FOUND" not in ctl_output.content | join

    # IMS already up and a new 'Create' comes in, fail it with 'failedDup' status
    - block:
        - name: Update CR instance run status
          include_role:
            name: update_instance_status
          vars:
            status_key: 'run_result'
            status_val: 'failedDup'
            instance_kind: TMDB
        - fail:
            msg: Duplidate IMS {{ DFS_IMS_SSID }}
      when: 
        - not reconcile_run
        - ctl_output.content is defined and "NOT FOUND" not in ctl_output.content | join 