---
#
# Copyright 2023 IBM Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Tasks for IMS Connect (ICON)
- name: Resource Manager
  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims
  vars:
      icon_not_up: false

  block:

    - name: Check if {{ DFS_IMS_SSID }}HWS already Up
      zos_operator:
        cmd: 'd a,{{ DFS_IMS_SSID }}HWS'
      register: cmd_output
    - set_fact:
        icon_not_up: true
      when: cmd_output.content is defined and "NOT FOUND" in cmd_output.content | join

    # AL: Use mvs_raw to replace JCL
    - set_fact:
        bpe_icon_config: '{{ role_path }}/templates/bpe_icon_config.txt'
        icon_config: '{{ role_path }}/templates/icon_config.txt'
        icon_proc: '{{ role_path }}/templates/icon_proc.txt'

    - name: Define BPECONFG
      zos_mvs_raw:
        pgm: IEBGENER
        auth: false
        dds:
          - dd_data_set:
              dd_name: sysut2
              data_set_name: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB(BPECFIV)"
              disposition: shr
          - dd_dummy:
              dd_name: sysin
          - dd_input:
              dd_name: sysut1
              content: "{{ lookup('template', '{{ bpe_icon_config }}') }}"
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
      when: icon == "config" and ( not reconcile_run or (reconcile_run and tmdb_cr_instance.resources[0].status.run_result == 'failedInputValidation') )

    - name: Add HWSCFODB member
      zos_mvs_raw:
        pgm: IEBGENER
        auth: false
        dds:
          - dd_data_set:
              dd_name: sysut2
              data_set_name: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB(HWSCFODB)"
              disposition: shr
          - dd_dummy:
              dd_name: sysin
          - dd_input:
              dd_name: sysut1
              content: "{{ lookup('template', '{{ icon_config }}') }}"
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
      when: icon == "config" and ( not reconcile_run or (reconcile_run and tmdb_cr_instance.resources[0].status.run_result == 'failedInputValidation') )

    - name: Add ICON member to PROCLIB
      zos_mvs_raw:
        pgm: IEBGENER
        auth: false
        dds:
          - dd_data_set:
              dd_name: sysut2
              data_set_name: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB({{ DFS_IMS_SSID }}HWS)"
              disposition: shr
          - dd_dummy:
              dd_name: sysin
          - dd_input:
              dd_name: sysut1
              content: "{{ lookup('template', '{{ icon_proc }}') }}"
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
      when: icon == "config" and ( not reconcile_run or (reconcile_run and tmdb_cr_instance.resources[0].status.run_result == 'failedInputValidation') )

    # Start ICON
    - name: Start ICON
      zos_operator:
        cmd: 's {{ DFS_IMS_SSID }}HWS'
        verbose: true
      when: 
        - icon == "start"
        - icon_not_up

    # Stop ICON
    - name: Stop ICON
      zos_operator:
        cmd: 'c {{ DFS_IMS_SSID }}HWS'
        verbose: true
      when: icon == "stop" and not icon_not_up

    # Query ICON status
    - name: Query ICON status
      ims_command:
        command: QUERY IMSPLEX NAME(*) TYPE(ICON) SHOW(STATUS)
        plex:  '{{ DFS_IMSPlex }}'
      when: icon == "query"