---
###############################################################################
# © Copyright IBM Corporation 2023
###############################################################################
# Online Change Services
- name: Online Change Services
  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims

  block:

    # - block:
    - name: Enable IMS OLC
      command: 'jsub -f {{ uss_file_path }}/DFSENOLC.j2'
      # zos_job_submit: 
      #   max_rc: 16
      #   src: '{{ uss_file_path }}/DFSENOLC.j2'
      #   location: USS
      #   wait: "{{ zos_job_submit_wait }}"
      #   wait_time_s: "{{ zos_job_submit_wait_s }}"
      #   return_output: "{{ zos_job_submit_return_output }}"
      when: enable_olc and ( not reconcile_run or (reconcile_run and tmdb_cr_instance.resources[0].status.run_result == 'failedDup') )


    # We need a module for the online change utility, no way around it
    - name: Establish active libs
      command: 'jsub -f {{ uss_file_path }}/DFS4ACTV.j2'
      # zos_job_submit: 
      #   max_rc: 16
      #   src: '{{ uss_file_path }}/DFS4ACTV.j2'
      #   location: USS
      #   wait: "{{ zos_job_submit_wait }}"
      #   wait_time_s: "{{ zos_job_submit_wait_s }}"
      #   return_output: "{{ zos_job_submit_return_output }}"
      when: active_libs and ( not reconcile_run or (reconcile_run and tmdb_cr_instance.resources[0].status.run_result == 'failedDup') )