#
# Copyright 2023 IBM Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
namespace: ibm
name: zos_ims_operator
version: 1.1.0
readme: README.md
authors:
  - IBM Support <support@ibm.com>
description: >-
  The IBM IMS Operator Collection includes roles and playbooks used for provisioning IMS on a Wazi sandbox
license_file: LICENSE
tags:
  - ibm
  - z
  - zos
  - z_os
  - core
  - zos_core
  - data_set
  - jcl
  - uss
  - mvs
  - ims
  - zos_ims
  - z_and_cloud_modernization_stack_operator
  - zoscb
dependencies:
  ibm.ibm_zos_core: '>=1.3.5'
  ibm.ibm_zos_ims: '>=1.2.0'
repository: 'https://github.com/ibm/zos_ims_operator'

# The URL to any online docs
documentation: https://www.ibm.com/docs/SSV97FN_latest/ims-operator/overview.html

# The URL to the homepage of the collection/project
homepage: https://www.ibm.com/products/z-and-cloud-modernization-stack
build_ignore:
  - yamllint.yaml
  - .gitignore
  - gh-pages
  - '*.tar.gz'
  - .vscode 
  - handlers 
  - inventories 
  - icon 
  - tests 
  - .release-it.yml 
  - .travis.yml 
  - ansible.cfg.saved 
  - CHANGELOG.md 
  - no-ansible.cfg
  - run-delete-ims-datasets
  - run-deprov-wazi 
  - run-prov-wazi 
  - update-operator.sh 
  - build
  - Jenkinsfile
  - ansible-lint-config.yml
  - Dockerfile 
  - playbooks/test.yml
  - playbooks/delete-ims-datasets.yml
  - .whitesource
  
