---
#
# Copyright 2023 IBM Inc. All Rights Reserved
# SPDX-License-Identifier: Apache-2.0
#
# tasks file for proclib
- name: Proclib operations
  collections:
    - ibm.ibm_zos_core

  block:

    - name: Add IMS procs
      command: 'jsub -f {{ uss_file_path }}/DFSE302J.j2'
      # zos_job_submit: 
      #   max_rc: 16
      #   src: '{{ uss_file_path }}/DFSE302J.j2'
      #   location: USS
      #   wait: "{{ zos_job_submit_wait }}"
      #   wait_time_s: "{{ zos_job_submit_wait_s }}"
      #   return_output: "{{ zos_job_submit_return_output }}"
      when: add and ( not reconcile_run or (reconcile_run and tmdb_cr_instance.resources[0].status.run_result == 'failedDup') )

    - name: Define IMS subcomponents
      command: 'jsub -f {{ uss_file_path }}/DFSE303J.j2'
      # zos_job_submit: 
      #   max_rc: 16
      #   src: '{{ uss_file_path }}/DFSE303J.j2'
      #   location: USS
      #   wait: "{{ zos_job_submit_wait }}"
      #   wait_time_s: "{{ zos_job_submit_wait_s }}"
      #   return_output: "{{ zos_job_submit_return_output }}"
      when: bpeconfg


    - name: Copy procs in IMS PROCLIB
      command: 'jsub -f {{ uss_file_path }}/DFS4CPYP.j2'
      # zos_job_submit: 
      #   max_rc: 16
      #   src: '{{ uss_file_path }}/DFS4CPYP.j2'
      #   location: USS
      #   wait: "{{ zos_job_submit_wait }}"
      #   wait_time_s: "{{ zos_job_submit_wait_s }}"
      #   return_output: "{{ zos_job_submit_return_output }}"
      when: copy and ( not reconcile_run or (reconcile_run and tmdb_cr_instance.resources[0].status.run_result == 'failedDup') )

    - name: Copy procs to jobs dataset
      command: 'jsub -f {{ uss_file_path }}/DFSE313J.j2'
      # zos_job_submit: 
      #   max_rc: 16
      #   src: '{{ uss_file_path }}/DFSE313J.j2'
      #   location: USS
      #   wait: "{{ zos_job_submit_wait }}"
      #   wait_time_s: "{{ zos_job_submit_wait_s }}"
      #   return_output: "{{ zos_job_submit_return_output }}"
      when: copy_to_jobs and ( not reconcile_run or (reconcile_run and tmdb_cr_instance.resources[0].status.run_result == 'failedDup') )

    - name: Copy staging libs
      command: 'jsub -f {{ uss_file_path }}/DFSCPYST.j2'
      # zos_job_submit: 
      #   max_rc: 16
      #   src: '{{ uss_file_path }}/DFSCPYST.j2'
      #   location: USS
      #   wait: "{{ zos_job_submit_wait }}"
      #   wait_time_s: "{{ zos_job_submit_wait_s }}"
      #   return_output: "{{ zos_job_submit_return_output }}"
      when: copy_stage_libs and ( not reconcile_run or (reconcile_run and tmdb_cr_instance.resources[0].status.run_result == 'failedDup') )


    - name: Create additional sample procedures
      command: 'jsub -f {{ uss_file_path }}/DFSPROCB.j2'
      # zos_job_submit: 
      #   max_rc: 16
      #   src: '{{ uss_file_path }}/DFSPROCB.j2'
      #   location: USS
      #   wait: "{{ zos_job_submit_wait }}"
      #   wait_time_s: "{{ zos_job_submit_wait_s }}"
      #   return_output: "{{ zos_job_submit_return_output }}"
      when: create_sample

    - name: Clean zCloud PROCLIB
      zos_data_set:
        batch:
          - name: '{{ zCloud_PROCLIB }}({{ DFS_IMS_SSID }}CTL)'
            state: absent
            type: MEMBER
          - name: '{{ zCloud_PROCLIB }}({{ DFS_IMS_SSID }}DLI)'
            state: absent
            type: MEMBER
          - name: '{{ zCloud_PROCLIB }}({{ DFS_IMS_SSID }}DRC)'
            state: absent
            type: MEMBER
          - name: '{{ zCloud_PROCLIB }}({{ DFS_IMS_SSID }}OM)'
            state: absent
            type: MEMBER
          - name: '{{ zCloud_PROCLIB }}({{ DFS_IMS_SSID }}SCI)'
            state: absent
            type: MEMBER
          - name: '{{ zCloud_PROCLIB }}({{ DFS_IMS_SSID }}RM)'
            state: absent
            type: MEMBER
          - name: '{{ zCloud_PROCLIB }}({{ DFS_IMS_SSID }}ODBM)'
            state: absent
            type: MEMBER
      when: delete
      #ignore_errors: true