---
###############################################################################
# © Copyright IBM Corporation 2023
###############################################################################
# Tasks for Operations Manager (OM)
- name: Operations Manager
  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims
  vars:
        om_not_up: false
        
  block:

    - name: Check if {{ DFS_IMS_SSID }}OM already Up
      zos_operator:
        cmd: 'd a,{{ DFS_IMS_SSID }}OM'
      register: cmd_output
    - set_fact:
        om_not_up: true
      when: cmd_output.content is defined and "NOT FOUND" in cmd_output.content | join
    - set_fact:
        bpe_config: '{{ role_path }}/templates/bpe_config.txt'
        oi_config: '{{ role_path }}/templates/oi_config.txt'
        om_config: '{{ role_path }}/templates/om_config.txt'
        rom_config: '{{ role_path }}/templates/rom_config.txt'

    # AL: This code works, but OM doesn't start
    - name: Define BPECONFG
      zos_mvs_raw:
        pgm: IEBGENER
        auth: false
        dds:
          - dd_data_set:
              dd_name: sysut2
              data_set_name: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB(BPECONFG)"
              disposition: shr
          - dd_dummy:
              dd_name: sysin
          - dd_input:
              dd_name: sysut1
              content: "{{ lookup('template', '{{ bpe_config }}') }}"
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
      when: om == "config" and not reconcile_run

    - name: Add CSLOI000 member
      zos_mvs_raw:
        pgm: IEBGENER
        auth: false
        dds:
          - dd_data_set:
              dd_name: sysut2
              data_set_name: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB(CSLOI000)"
              disposition: shr
          - dd_dummy:
              dd_name: sysin
          - dd_input:
              dd_name: sysut1
              content: "{{ lookup('template', '{{ oi_config }}') }}"
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
      when: om == "config" and not reconcile_run

    - name: Add OM member to PROCLIB
      zos_mvs_raw:
        pgm: IEBGENER
        auth: false
        dds:
          - dd_data_set:
              dd_name: sysut2
              data_set_name: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB({{ DFS_IMS_SSID }}OM)"
              disposition: shr
          - dd_dummy:
              dd_name: sysin
          - dd_input:
              dd_name: sysut1
              content: "{{ lookup('template', '{{ om_config }}') }}"
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
      when: om == "config" and not reconcile_run

    - name: Add CSLOIROM member
      zos_mvs_raw:
        pgm: IEBGENER
        auth: no
        dds:
          - dd_data_set:
              dd_name: sysut2
              data_set_name: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB(CSLOIROM)"
              disposition: shr
          - dd_dummy:
              dd_name: sysin
          - dd_input:
              dd_name: sysut1
              content: "{{ lookup('template', '{{ rom_config }}') }}"
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
      when: om == "config" and not reconcile_run

    # Start OM
    - name: Start OM
      zos_operator:
        cmd: 's {{ DFS_IMS_SSID }}OM'
        verbose: true
      when: 
        - om == "start"
        - om_not_up

    # Stop OM
    - name: Stop OM
      zos_operator:
        cmd: 'c {{ DFS_IMS_SSID }}OM'
        verbose: true
      when: om == "stop" and not om_not_up

    # Query OM status
    - name: Query OM status
      ims_command:
        command: QUERY IMSPLEX NAME(*) TYPE(OM) SHOW(STATUS)
        plex:  '{{ DFS_IMSPlex }}'
      when: om == "query"
