---
#
# Copyright 2023 IBM Inc. All Rights Reserved
# SPDX-License-Identifier: Apache-2.0
#
- name: Retrieve k8s context
  # when: k8s_managed
  block:
  - debug:
      msg:
      - '{{ k8s_managed }}'
      - '{{ k8s_cr_event }}'
      - '{{ k8s_cr_group }}'
      - '{{ k8s_cr_version }}'
      - '{{ k8s_cr_kind }}'
      - '{{ ansible_operator_meta.namespace }}'
      - '{{ ansible_operator_meta.name }}'

  - name: Retrieve the TMDB instance for {{ k8s_cr_event }} event
    k8s_info:
        api_version: '{{ k8s_cr_version }}'
        kind: TMDB
        name: '{{ ansible_operator_meta.name }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
    register: tmdb_cr_instance
    delegate_to: 127.0.0.1

  - debug:
      var: tmdb_cr_instance

  - name: set product version
    set_fact:
      DFS_IMS_SSID: '{{tmdb_cr_instance.resources[0].spec.DFS_IMS_SSID}}'
      DFS_IMSPlex: '{{tmdb_cr_instance.resources[0].spec.DFS_IMSPlex}}'
      ODBM_PORTID: "{{ tmdb_cr_instance.resources[0].spec.ODBM_PORTID }}"
      ODBM_SSLPORTID: "{{ tmdb_cr_instance.resources[0].spec.ODBM_SSLPORTID }}"
      IMS_CONNECT_PORT: "{{ tmdb_cr_instance.resources[0].spec.IMS_CONNECT_PORT }}"
      IMS_CONNECT_SSLPORT: "{{ tmdb_cr_instance.resources[0].spec.IMS_CONNECT_SSLPORT }}"
      DFS_AUTH_LIB_SYSHLQ1: "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_AUTH_LIB_SYSHLQ1 }}"
      DFS_AUTH_LIB_HLQ1: "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_AUTH_LIB_HLQ1 }}"
      DFS_SMS_ENVIRONMENT: "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_SMS_ENVIRONMENT }}"
      DFS_SMS_CLASS: "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_SMS_CLASS }}"
      STEPLIB: "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.STEPLIB }}"
      JOB_CLASS: "{{ tmdb_cr_instance.resources[0].spec.Optional_zOS_Configuration.JOB_CLASS }}"
      MSG_CLASS: "{{ tmdb_cr_instance.resources[0].spec.Optional_zOS_Configuration.MSG_CLASS }}"
      zCloud_PROCLIB: "{{ tmdb_cr_instance.resources[0].spec.Optional_zOS_Configuration.zCloud_PROCLIB }}"
      zCloud_LERuntime: "{{ tmdb_cr_instance.resources[0].spec.Optional_zOS_Configuration.zCloud_LERuntime }}"
      zCloud_MACLIB: "{{ tmdb_cr_instance.resources[0].spec.Optional_zOS_Configuration.zCloud_MACLIB }}"
      zCloud_CSSLIB: "{{ tmdb_cr_instance.resources[0].spec.Optional_zOS_Configuration.zCloud_CSSLIB }}"
      instance_creationTime: "{{ tmdb_cr_instance.resources[0].metadata.creationTimestamp[0:15]}}"
      instance_lastTransitionTime: "{{ tmdb_cr_instance.resources[0].status.conditions[0].lastTransitionTime[0:15]}}"
      reconcile_run: false
      ims_is_up: false
      active_hws_jobid: ""
  

  - name: set optional volume
    set_fact:
      DFS_DS_VOLUME1: "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_DS_VOLUME1 }}"
    when: tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_DS_VOLUME1 is defined

  - name: set optional DFS_AUTH_LIB_SYSHLQ2
    set_fact:
      DFS_AUTH_LIB_SYSHLQ2: "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_AUTH_LIB_SYSHLQ2 }}"
    when: tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_AUTH_LIB_SYSHLQ2 is defined
      
  - name: set optional DFS_AUTH_LIB_HLQ2
    set_fact:    
      DFS_AUTH_LIB_HLQ2: "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_AUTH_LIB_HLQ2 }}"
    when: tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_AUTH_LIB_HLQ2 is defined

  - debug:
      msg: 
        - '{{instance_creationTime}}'
        - '{{instance_lastTransitionTime}}'

  - debug:
      var: tmdb_cr_instance.resources[0].status

  - debug:
      msg:
        - '{{tmdb_cr_instance.resources[0].spec.DFS_IMS_SSID}}'
        - '{{tmdb_cr_instance.resources[0].spec.DFS_IMSPlex}}'
        - '{{tmdb_cr_instance.resources[0].spec.ODBM_PORTID}}'
        - '{{tmdb_cr_instance.resources[0].spec.ODBM_SSLPORTID}}'
        - '{{tmdb_cr_instance.resources[0].spec.IMS_CONNECT_PORT}}'
        - '{{tmdb_cr_instance.resources[0].spec.IMS_CONNECT_SSLPORT}}'
        - '{{DFS_IMS_SSID}}'
        - '{{DFS_IMSPlex}}'
        - '{{ODBM_PORTID}}'
        - '{{ODBM_SSLPORTID}}'
        - '{{IMS_CONNECT_PORT}}'
        - '{{IMS_CONNECT_SSLPORT}}'
        - '{{reconcile_run}}'
        - '{{ims_is_up}}'
        - '{{DFS_AUTH_LIB_SYSHLQ1}}'
        - "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_AUTH_LIB_SYSHLQ1 }}"
        - '{{DFS_AUTH_LIB_SYSHLQ2}}'
        - '{{DFS_AUTH_LIB_HLQ1}}'
        - "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_AUTH_LIB_HLQ1 }}"
        - '{{DFS_AUTH_LIB_HLQ2}}'
        - '{{DFS_SMS_ENVIRONMENT}}'
        - "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_SMS_ENVIRONMENT }}"
        - '{{DFS_SMS_CLASS}}'
        - "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_SMS_CLASS }}"
        - '{{STEPLIB}}'
        - "{{ tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.STEPLIB }}"
        - '{{JOB_CLASS}}'
        - "{{ tmdb_cr_instance.resources[0].spec.Optional_zOS_Configuration.JOB_CLASS }}"
        - '{{MSG_CLASS}}'
        - "{{ tmdb_cr_instance.resources[0].spec.Optional_zOS_Configuration.MSG_CLASS }}"
        - '{{zCloud_PROCLIB}}'
        - "{{ tmdb_cr_instance.resources[0].spec.Optional_zOS_Configuration.zCloud_PROCLIB }}"
        - '{{zCloud_LERuntime}}'
        - "{{ tmdb_cr_instance.resources[0].spec.Optional_zOS_Configuration.zCloud_LERuntime }}"
        - '{{zCloud_MACLIB}}'
        - "{{ tmdb_cr_instance.resources[0].spec.Optional_zOS_Configuration.zCloud_MACLIB }}"
        - '{{zCloud_CSSLIB}}'
        - "{{ tmdb_cr_instance.resources[0].spec.Optional_zOS_Configuration.zCloud_CSSLIB }}"

  - name: This run is due to reconcile
    set_fact:
      reconcile_run: true
    when: tmdb_cr_instance.resources[0].status.run_result is defined

- name: Retrieve z/OS proclib dataset
  shell: pproc
  register: proclib_ds

# JOB_CARD will be the default job card inserted for dynamically generated JCL
# ensure MSGCLASS and CLASS are correct for desired environment
- set_fact:
    JOB_CARD: |-
      //ANSIBLE JOB 'testing',
      //*  NOTIFY={{ TARGET_USERNAME | upper }},
      //  USER={{ TARGET_USERNAME | upper }},
      //  MSGCLASS={{ MSG_CLASS }},
      //  MSGLEVEL=(1,1),
      //  CLASS={{ JOB_CLASS }}
    ODBM_JOB_CARD: |-
          //{{ DFS_IMS_SSID }}ODBM JOB 'testing',
          //*  NOTIFY={{ TARGET_USERNAME | upper }},
          //  USER={{ TARGET_USERNAME | upper }},
          //  MSGCLASS={{ MSG_CLASS }},
          //  MSGLEVEL=(1,1),
          //  CLASS={{ JOB_CLASS }}
    IST_VTAM_IMSAPPLID: '{{ DFS_IMS_SSID }}'
    ADDTL_SAMP_PROC_LIB: '{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB'
    TCPIP_PROFILE_TMP: '{{ DFS_AUTH_LIB_HLQ1 }}.TEMP'
    ROUTE: '{{ DFS_IMS_SSID }}'
    ZOS_RELEASE: '{{proclib_ds.stdout[5:9]}}'
    DFS_DS_VOLUME2: '{{proclib_ds.stdout[8]}}{{proclib_ds.stdout[7]}}USR1'

- debug:
    var: 
      - ZOS_RELEASE
      - DFS_DS_VOLUME1

- set_fact: 
    DFS_DS_VOLUME1: '{{proclib_ds.stdout[8]}}{{proclib_ds.stdout[7]}}USR1'
  when: tmdb_cr_instance.resources[0].spec.Optional_IMS_Configuration.DFS_DS_VOLUME1 is not defined

- set_fact:
    system_environment: '{{ system_environment | combine(new_item, recursive=true) }}'
  vars:
    new_item: { STEPLIB: '{{ STEPLIB }}' }
  with_dict: '{{ system_environment }}'

- block:

  - name: Create temporary directory to store templates
    tempfile:
      state: directory
    register: this_tmp_dir
    when: tmdb_cr_instance.resources[0].status.templates_path is not defined

  - name: Set temporary directory to store templates
    set_fact:
      tmdb_tmp_dir: '{{this_tmp_dir.path}}'
    when: tmdb_cr_instance.resources[0].status.templates_path is not defined

  - name: Overwrite template path with existing one for reconcile run
    set_fact:
      tmdb_tmp_dir: '{{tmdb_cr_instance.resources[0].status.templates_path}}'
    when: tmdb_cr_instance.resources[0].status.templates_path is defined

  - set_fact:
      DFS_AUTH_LIB_SYSHLQ: "{% if DFS_AUTH_LIB_SYSHLQ2 %}{{DFS_AUTH_LIB_SYSHLQ1}}.{{DFS_AUTH_LIB_SYSHLQ2}}{% else %}{{DFS_AUTH_LIB_SYSHLQ1}}{% endif %}"

  - debug:
      msg: IMS source location is '{{ DFS_AUTH_LIB_SYSHLQ }}'