---
#
# Copyright 2023 IBM Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Check if IMS already up
- name: Check for duplicate IMS
  collections:
      - ibm.ibm_zos_core
      - ibm.ibm_zos_ims
      
  block:
      - name: Get XCF group CSL{{DFS_IMSPlex}} members
        zos_operator:
          cmd: 'D XCF,GROUP,CSL{{DFS_IMSPlex}}'
        register: cmd_output

      - set_fact:
          imsplex_is_up: true
        when: 
          - cmd_output.content[3] is defined
          - '"NOT DEFINED" not in cmd_output.content[3] | join'

      # Reconcile run and not failedInputValidation, try to reconcile
      - block:
          - name: IMSPLEX {{DFS_IMSPlex}} already Up. Trying to reconcile...
            debug: 
              msg: ''
        when: 
          - reconcile_run
          - imsplex_is_up
          - tmdb_cr_instance.resources[0].status.run_result != 'failedInputValidation'

      # Reconcile run and failedInputValidation, fail it
      - block:
          - fail:
              msg: Duplicate IMSPlex {{ DFS_IMSPlex }}. Please use a different IMSPlex name. 
        when: 
          - reconcile_run
          - imsplex_is_up
          - tmdb_cr_instance.resources[0].status.run_result == 'failedInputValidation'

      # IMSPex already up and a new 'Create' comes in, fail it with 'failedInputValidation' status
      - block: 
        - name: Update CR instance run status
          include_role:
            name: update_instance_status
          vars:
            status_val: 'failedInputValidation'
            status_key: 'run_result'
            instance_kind: TMDB
        - fail:
            msg: Duplicate IMSPlex {{ DFS_IMSPlex }}
        when: 
          - not reconcile_run
          - cmd_output.content[3] is defined
          - '"NOT DEFINED" not in cmd_output.content[3] | join'