---
###############################################################################
# © Copyright IBM Corporation 2023
###############################################################################
# Check if IMS already up
- name: Check for duplicate IMS
  collections:
      - ibm.ibm_zos_core
      - ibm.ibm_zos_ims
      
  block:
      - name: Get XCF group CSL{{DFS_IMSPlex}} members
        zos_operator:
          cmd: 'D XCF,GROUP,CSL{{DFS_IMSPlex}}'
        register: cmd_output

      # Reconcile run and instance not in 'failedDup' status
      - block:
          - debug: 
              msg: 'IMSPLEX {{DFS_IMSPlex}} already Up. Trying to reconcile...'
          # - meta: end_host
        when: 
          - reconcile_run
          - cmd_output.content[3] is defined
          - '"NOT DEFINED" not in cmd_output.content[3] | join'
          # - tmdb_cr_instance.resources[0].status.run_result is defined and tmdb_cr_instance.resources[0].status.run_result != 'failedDup'

      # IMSPex already up and a new/recon 'Create' comes in, fail it with 'failedDup' status
      - block: 
        - name: Update CR instance run status
          include_role:
            name: update_instance_status
          vars:
            status_val: 'failedDup'
            status_key: 'run_result'
            instance_kind: TMDB
        - fail:
            msg: Duplicate IMSPlex {{ DFS_IMSPlex }}
        when: 
          - not reconcile_run
          - cmd_output.content[3] is defined
          - '"NOT DEFINED" not in cmd_output.content[3] | join'