---
#
# Copyright 2023 IBM Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Common services for provision-ims-dbdc
- name: Provision IMS
  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims
  vars:
      icon_not_up: false
      ims_not_up: false
  block:
    - name: Check if {{ DFS_IMS_SSID }}CTL already Up
      zos_operator:
        cmd: 'd a,{{ DFS_IMS_SSID }}CTL'
      register: cmd_output

    - set_fact:
        ims_not_up: true
      when: cmd_output.content is defined and "NOT FOUND" in cmd_output.content | join

    # Start IMS control region if start_ctl is true
    - name: Start IMS control region
      zos_operator:
        cmd: 's {{ DFS_IMS_SSID }}CTL'
        verbose: true
      when: ctl == "start" and ims_not_up

    # Stop IMS control region
    - name: Stop IMS control region
      zos_operator:
        cmd: 'c {{ DFS_IMS_SSID }}CTL'
        verbose: true
      when: ctl == "stop" and not ims_not_up
      #ignore_errors: true

    - name: Issue DIS ACT command
      ims_command:
        command: /DIS ACT
        plex: '{{ DFS_IMSPlex }}'
      register: display_cmd_output
      failed_when: display_cmd_output.msg is not defined

    - name: IMS cold start
      ims_command:
        command:  NRE CHECKPOINT 0 FMT ALL
        plex:  '{{ DFS_IMSPlex }}'
        route: '{{ DFS_IMS_SSID }}'
      when: 
        - cold_start 
        - display_cmd_output.msg is defined and "Success" not in display_cmd_output.msg | join

      register: cold_start_result

    # - debug:
    #     var:
    #       - cold_start
    #       - cold_start_result

    # - name: Try ERE if cold start didn't work
    #   ims_command:
    #     command:  ERE OVERRIDE.
    #     plex:  '{{ DFS_IMSPlex }}'
    #     route: '{{ DFS_IMS_SSID }}'
    #   when: cold_start and cold_start_result.stdout.failed

    - name: Check if {{ DFS_IMS_SSID }}HWS already Up
      zos_operator:
        cmd: 'd a,{{ DFS_IMS_SSID }}HWS'
      register: cmd_output
    - set_fact:
        icon_not_up: true
      when: cmd_output.content is defined and "NOT FOUND" in cmd_output.content | join

    - name: ICON start
      command: "jsub {{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_IMS_SSID }}.JOBS({{ DFS_IMS_SSID }}HWS1)"
      # zos_job_submit: 
      #   max_rc: 16
      #   src: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_IMS_SSID }}.JOBS({{ DFS_IMS_SSID }}HWS1)"
      #   location: DATA_SET
      #   wait: "{{ zos_job_submit_wait }}"
      #   wait_time_s: "{{ zos_job_submit_wait_s }}"
      #   return_output: "{{ zos_job_submit_return_output }}"
      when: 
        - icon == "start"
        - icon_not_up


    # Start IMS Connect
    # - name: Start ICON
    #   zos_operator:
    #     cmd: 's {{ DFS_IMS_SSID }}HWS1'
    #     verbose: true
    #   when: 
    #     - icon == "start"
    #     - icon_not_up

    # Stop ICON
    - name: Stop ICON
      zos_operator:
        cmd: 'c {{ DFS_IMS_SSID }}HWS'
        verbose: true
      when: icon == "stop" and not icon_not_up