###############################################################################
# © Copyright IBM Corporation 2023
###############################################################################
# vars file for set_up_run_environment