---
###############################################################################
# © Copyright IBM Corporation 2023
###############################################################################
  # sysdef services
  - name: System Definition Services
    collections:
      - ibm.ibm_zos_core
      - ibm.ibm_zos_ims

    block:

      - block:

        - name: IMS system definition preprocessor utility
          command: 'jsub -f {{ uss_file_path }}/DFSGNPRE.j2'
          # zos_job_submit: 
          #   max_rc: 16
          #   src: '{{ uss_file_path }}/DFSGNPRE.j2'
          #   location: USS
          #   wait: "{{ zos_job_submit_wait }}"
          #   wait_time_s: "{{ zos_job_submit_wait_s }}"
          #   return_output: "{{ zos_job_submit_return_output }}"
          # when: preprocess
          when: preprocess and ( not reconcile_run or (reconcile_run and tmdb_cr_instance.resources[0].status.run_result == 'failedDup') )

      - block:

        - name: Sysdef stage 1
          command: 'jsub -f {{ uss_file_path }}/DFS4STG1.j2'
          # zos_job_submit: 
          #   max_rc: 16
          #   src: '{{ uss_file_path }}/DFS4STG1.j2'
          #   location: USS
          #   wait: "{{ zos_job_submit_wait }}"
          #   wait_time_s: "{{ zos_job_submit_wait_s }}"
          #   return_output: "{{ zos_job_submit_return_output }}"
          # when: stage1
          when: stage1 and ( not reconcile_run or (reconcile_run and tmdb_cr_instance.resources[0].status.run_result == 'failedDup') )


      - block:

        - name: Sysdef stage 2
          command: 'jsub -f {{ uss_file_path }}/DFS4STG2.j2'
          # zos_job_submit: 
          #   max_rc: 16
          #   src: '{{ uss_file_path }}/DFS4STG2.j2'
          #   location: USS
          #   wait: "{{ zos_job_submit_wait }}"
          #   wait_time_s: "{{ zos_job_submit_wait_s }}"
          #   return_output: "{{ zos_job_submit_return_output }}"
          # when: stage2
          when: stage2 and ( not reconcile_run or (reconcile_run and tmdb_cr_instance.resources[0].status.run_result == 'failedDup') )
