###############################################################################
# © Copyright IBM Corporation 2023
###############################################################################
# vars file for check_duplicate_ims
