---
#
# Copyright 2023 IBM Inc. All Rights Reserved
# SPDX-License-Identifier: Apache-2.0
#
- name: IMS TMDB De-provisioning
  hosts: all
  gather_facts: false
  # * Include different variable files depending on environment/inventory used
  vars_files:
    - vars_wazi/ims-dbdc.yml
  environment: '{{ system_environment }}'

  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims
    - operator_sdk.util

  tasks:
    - include_role:
        name: set_up_run_environment

    - block:
        # Do not de-provision IMS if the instance is in 'failedDup' status
        - block:
            - name: Failed duplicate instance found. No de-provisioning. Exiting....
              debug: 
                  msg: ''
            - meta: end_host
          when: 
            - tmdb_cr_instance.resources[0].status.run_result is defined 
            - tmdb_cr_instance.resources[0].status.run_result == 'failedDup'
            # - k8s_managed

        - include_role:
            name: deprovision_ims

      always:
        - block:
          - debug:
              var: ansible_failed_task
          when: ansible_failed_task is defined
        - block:
          - debug:
              var: ansible_failed_result
          when: ansible_failed_result is defined
        - name: Delete the temporary provision files directory {{ tmdb_tmp_dir.path }}
          file:
            path: "{{ tmdb_tmp_dir.path }}"
            state: absent
          when: tmdb_cr_instance.resources[0].status.run_result is defined and tmdb_cr_instance.resources[0].status.run_result == 'Deprovision completed'

      vars:
        uss_file_path: '{{ tmdb_tmp_dir.path }}'


  handlers:
    - include: handlers/handlers.yml