---
#
# Copyright 2023 IBM Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
- name: IMS TMDB De-provisioning
  hosts: all
  gather_facts: false
  # * Include different variable files depending on environment/inventory used
  vars_files:
    - vars_wazi/ims-dbdc.yml
    - vars_wazi/ims-zos.yml
  environment: '{{ system_environment }}'

  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims
    - operator_sdk.util

  tasks:

    - block:
        # Do not de-provision IMS if the instance is in 'failedInputValidation' status
        - block:
            - name: Failed duplicate instance found. No de-provisioning. Exiting....
              debug: 
                  msg: ''
            - meta: end_host
          when: 
            - tmdb_cr_instance.resources[0].status.run_result is defined 
            - tmdb_cr_instance.resources[0].status.run_result == 'failedInputValidation'
            # - k8s_managed

        - name: Deprovisioning starting.... 
          include_role:
            name: update_instance_status
          vars:
            status_key: 'run_result'
            status_val: 'Deprovisioning in progress...'
            instance_kind: TMDB

        - include_role:
            name: set_up_run_environment

        - include_role:
            name: deprovision_ims
        
        - name: Update CR instance run status
          include_role:
            name: update_instance_status
          vars:
            status_key: 'run_result'
            status_val: 'Deprovision completed'
            instance_kind: TMDB
    
        - name: Deprovisioning Complete!
          meta: noop

      always:
        # - block:
        #   - debug:
        #       var: ansible_failed_task
        #   when: ansible_failed_task is defined
        # - block:
        #   - debug:
        #       var: ansible_failed_result
        #   when: ansible_failed_result is defined
        - name: Delete the temporary provision files directory {{ tmdb_tmp_dir.path }}
          file:
            path: "{{ tmdb_tmp_dir.path }}"
            state: absent
        - name: clean up files that zoau leaves behind
          shell: rm /tmp/{{item}}*
          with_sequence: 0-9
          register: output
          failed_when: output.rc | int > 1

      vars:
        uss_file_path: '{{ tmdb_tmp_dir.path }}'


  # handlers:
  #   - include: handlers/handlers.yml